name: Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore fintech.sln

      - name: Build solution
        run: dotnet build fintech.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test fintech.sln --configuration Release --no-build
